name: CD

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Release
        continue-on-error: true

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      - name: Setup project
        run: yarn setup

      - name: Build project
        env:
          CHAINLINK_VERSION: 1.8.0@UNKNOWN
          CHAINLINK_BASEURL: '' 
        run: yarn build

      - name: Create Release Pull Request 
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Change directory to release scripts
        run: cd scripts

      - name: Run yarn install for scripts
        run: yarn install --frozen-lockfile

      # If we have changesets, that means that we have not done an official release yet,
      # as when releases are created, all changesets are consumed.
      # Indexing a JSON array via truthy evaluation results in index 1, whereas a falsy evaluation results in index 0
      - name: Create ${{ fromJSON('["Official","Snapshot"]')[ steps.changesets.outputs.hasChangesets == 'true'] }} Release 
        env:
          HAS_CHANGES: ${{ steps.changesets.outputs.hasChangesets }}
          GH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: yarn -s release
