name: CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Unit Tests
        continue-on-error: true

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      - name: Setup project
        run: yarn setup

      - name: Run tests
        run: yarn run test:ciA
        
      - name: Upload coverage
        run: ./bin/codecov -s operator_ui/coverage
