name: Operator UI

on:
  push:
  pull_request:

jobs:
  operator-ui:
    name: Operator UI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Operator UI Tests
        continue-on-error: true
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: |
            ~/.npm
            ~/.cache
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run yarn install
        run: yarn install --frozen-lockfile
      - name: Run Operator UI tests
        run: ./scripts/operator_ui_test
